// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: portfolio/v1/portfolio.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportFormat int32

const (
	ExportFormat_EXPORT_FORMAT_UNSPECIFIED ExportFormat = 0
	ExportFormat_EXPORT_FORMAT_CSV         ExportFormat = 1
	ExportFormat_EXPORT_FORMAT_JSON        ExportFormat = 2
)

// Enum value maps for ExportFormat.
var (
	ExportFormat_name = map[int32]string{
		0: "EXPORT_FORMAT_UNSPECIFIED",
		1: "EXPORT_FORMAT_CSV",
		2: "EXPORT_FORMAT_JSON",
	}
	ExportFormat_value = map[string]int32{
		"EXPORT_FORMAT_UNSPECIFIED": 0,
		"EXPORT_FORMAT_CSV":         1,
		"EXPORT_FORMAT_JSON":        2,
	}
)

func (x ExportFormat) Enum() *ExportFormat {
	p := new(ExportFormat)
	*p = x
	return p
}

func (x ExportFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_portfolio_v1_portfolio_proto_enumTypes[0].Descriptor()
}

func (ExportFormat) Type() protoreflect.EnumType {
	return &file_portfolio_v1_portfolio_proto_enumTypes[0]
}

func (x ExportFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportFormat.Descriptor instead.
func (ExportFormat) EnumDescriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{0}
}

type GetPortfolioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioRequest) Reset() {
	*x = GetPortfolioRequest{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioRequest) ProtoMessage() {}

func (x *GetPortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioRequest.ProtoReflect.Descriptor instead.
func (*GetPortfolioRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{0}
}

func (x *GetPortfolioRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	UsdValue      float64                `protobuf:"fixed64,5,opt,name=usd_value,json=usdValue,proto3" json:"usd_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{1}
}

func (x *Asset) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *Asset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Asset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Asset) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Asset) GetUsdValue() float64 {
	if x != nil {
		return x.UsdValue
	}
	return 0
}

type GetPortfolioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Assets        []*Asset               `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`
	TotalUsdValue float64                `protobuf:"fixed64,3,opt,name=total_usd_value,json=totalUsdValue,proto3" json:"total_usd_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioResponse) Reset() {
	*x = GetPortfolioResponse{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioResponse) ProtoMessage() {}

func (x *GetPortfolioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioResponse.ProtoReflect.Descriptor instead.
func (*GetPortfolioResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{2}
}

func (x *GetPortfolioResponse) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *GetPortfolioResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *GetPortfolioResponse) GetTotalUsdValue() float64 {
	if x != nil {
		return x.TotalUsdValue
	}
	return 0
}

type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Format        ExportFormat           `protobuf:"varint,2,opt,name=format,proto3,enum=portfolio.v1.ExportFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{3}
}

func (x *ExportRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *ExportRequest) GetFormat() ExportFormat {
	if x != nil {
		return x.Format
	}
	return ExportFormat_EXPORT_FORMAT_UNSPECIFIED
}

type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{4}
}

func (x *ExportResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_portfolio_v1_portfolio_proto protoreflect.FileDescriptor

const file_portfolio_v1_portfolio_proto_rawDesc = "" +
	"\n" +
	"\x1cportfolio/v1/portfolio.proto\x12\fportfolio.v1\"2\n" +
	"\x13GetPortfolioRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"\x8d\x01\n" +
	"\x05Asset\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1b\n" +
	"\tusd_value\x18\x05 \x01(\x01R\busdValue\"\x88\x01\n" +
	"\x14GetPortfolioResponse\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12+\n" +
	"\x06assets\x18\x02 \x03(\v2\x13.portfolio.v1.AssetR\x06assets\x12&\n" +
	"\x0ftotal_usd_value\x18\x03 \x01(\x01R\rtotalUsdValue\"`\n" +
	"\rExportRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x122\n" +
	"\x06format\x18\x02 \x01(\x0e2\x1a.portfolio.v1.ExportFormatR\x06format\"$\n" +
	"\x0eExportResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path*\\\n" +
	"\fExportFormat\x12\x1d\n" +
	"\x19EXPORT_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EXPORT_FORMAT_CSV\x10\x01\x12\x16\n" +
	"\x12EXPORT_FORMAT_JSON\x10\x022\xae\x01\n" +
	"\x10PortfolioService\x12U\n" +
	"\fGetPortfolio\x12!.portfolio.v1.GetPortfolioRequest\x1a\".portfolio.v1.GetPortfolioResponse\x12C\n" +
	"\x06Export\x12\x1b.portfolio.v1.ExportRequest\x1a\x1c.portfolio.v1.ExportResponseB[ZYgithub.com/aezizhu/million-dollar-hunter/services/portfolio-service/proto/portfolio/v1;v1b\x06proto3"

var (
	file_portfolio_v1_portfolio_proto_rawDescOnce sync.Once
	file_portfolio_v1_portfolio_proto_rawDescData []byte
)

func file_portfolio_v1_portfolio_proto_rawDescGZIP() []byte {
	file_portfolio_v1_portfolio_proto_rawDescOnce.Do(func() {
		file_portfolio_v1_portfolio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_portfolio_v1_portfolio_proto_rawDesc), len(file_portfolio_v1_portfolio_proto_rawDesc)))
	})
	return file_portfolio_v1_portfolio_proto_rawDescData
}

var file_portfolio_v1_portfolio_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_portfolio_v1_portfolio_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_portfolio_v1_portfolio_proto_goTypes = []any{
	(ExportFormat)(0),            // 0: portfolio.v1.ExportFormat
	(*GetPortfolioRequest)(nil),  // 1: portfolio.v1.GetPortfolioRequest
	(*Asset)(nil),                // 2: portfolio.v1.Asset
	(*GetPortfolioResponse)(nil), // 3: portfolio.v1.GetPortfolioResponse
	(*ExportRequest)(nil),        // 4: portfolio.v1.ExportRequest
	(*ExportResponse)(nil),       // 5: portfolio.v1.ExportResponse
}
var file_portfolio_v1_portfolio_proto_depIdxs = []int32{
	2, // 0: portfolio.v1.GetPortfolioResponse.assets:type_name -> portfolio.v1.Asset
	0, // 1: portfolio.v1.ExportRequest.format:type_name -> portfolio.v1.ExportFormat
	1, // 2: portfolio.v1.PortfolioService.GetPortfolio:input_type -> portfolio.v1.GetPortfolioRequest
	4, // 3: portfolio.v1.PortfolioService.Export:input_type -> portfolio.v1.ExportRequest
	3, // 4: portfolio.v1.PortfolioService.GetPortfolio:output_type -> portfolio.v1.GetPortfolioResponse
	5, // 5: portfolio.v1.PortfolioService.Export:output_type -> portfolio.v1.ExportResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_portfolio_v1_portfolio_proto_init() }
func file_portfolio_v1_portfolio_proto_init() {
	if File_portfolio_v1_portfolio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_portfolio_v1_portfolio_proto_rawDesc), len(file_portfolio_v1_portfolio_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_portfolio_v1_portfolio_proto_goTypes,
		DependencyIndexes: file_portfolio_v1_portfolio_proto_depIdxs,
		EnumInfos:         file_portfolio_v1_portfolio_proto_enumTypes,
		MessageInfos:      file_portfolio_v1_portfolio_proto_msgTypes,
	}.Build()
	File_portfolio_v1_portfolio_proto = out.File
	file_portfolio_v1_portfolio_proto_goTypes = nil
	file_portfolio_v1_portfolio_proto_depIdxs = nil
}
