// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: portfolio/v1/portfolio.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportFormat int32

const (
	ExportFormat_EXPORT_FORMAT_UNSPECIFIED ExportFormat = 0
	ExportFormat_EXPORT_FORMAT_CSV         ExportFormat = 1
	ExportFormat_EXPORT_FORMAT_JSON        ExportFormat = 2
)

// Enum value maps for ExportFormat.
var (
	ExportFormat_name = map[int32]string{
		0: "EXPORT_FORMAT_UNSPECIFIED",
		1: "EXPORT_FORMAT_CSV",
		2: "EXPORT_FORMAT_JSON",
	}
	ExportFormat_value = map[string]int32{
		"EXPORT_FORMAT_UNSPECIFIED": 0,
		"EXPORT_FORMAT_CSV":         1,
		"EXPORT_FORMAT_JSON":        2,
	}
)

func (x ExportFormat) Enum() *ExportFormat {
	p := new(ExportFormat)
	*p = x
	return p
}

func (x ExportFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_portfolio_v1_portfolio_proto_enumTypes[0].Descriptor()
}

func (ExportFormat) Type() protoreflect.EnumType {
	return &file_portfolio_v1_portfolio_proto_enumTypes[0]
}

func (x ExportFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportFormat.Descriptor instead.
func (ExportFormat) EnumDescriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{0}
}

type GetPortfolioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioRequest) Reset() {
	*x = GetPortfolioRequest{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioRequest) ProtoMessage() {}

func (x *GetPortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioRequest.ProtoReflect.Descriptor instead.
func (*GetPortfolioRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{0}
}

func (x *GetPortfolioRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	UsdValue      float64                `protobuf:"fixed64,5,opt,name=usd_value,json=usdValue,proto3" json:"usd_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{1}
}

func (x *Asset) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *Asset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Asset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Asset) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Asset) GetUsdValue() float64 {
	if x != nil {
		return x.UsdValue
	}
	return 0
}

type GetPortfolioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Assets        []*Asset               `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`
	TotalUsdValue float64                `protobuf:"fixed64,3,opt,name=total_usd_value,json=totalUsdValue,proto3" json:"total_usd_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioResponse) Reset() {
	*x = GetPortfolioResponse{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioResponse) ProtoMessage() {}

func (x *GetPortfolioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioResponse.ProtoReflect.Descriptor instead.
func (*GetPortfolioResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{2}
}

func (x *GetPortfolioResponse) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *GetPortfolioResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *GetPortfolioResponse) GetTotalUsdValue() float64 {
	if x != nil {
		return x.TotalUsdValue
	}
	return 0
}

type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Format        ExportFormat           `protobuf:"varint,2,opt,name=format,proto3,enum=portfolio.v1.ExportFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{3}
}

func (x *ExportRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *ExportRequest) GetFormat() ExportFormat {
	if x != nil {
		return x.Format
	}
	return ExportFormat_EXPORT_FORMAT_UNSPECIFIED
}

type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{4}
}

func (x *ExportResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Chain         string                 `protobuf:"bytes,3,opt,name=chain,proto3" json:"chain,omitempty"`
	TotalUsdValue float64                `protobuf:"fixed64,4,opt,name=total_usd_value,json=totalUsdValue,proto3" json:"total_usd_value,omitempty"`
	AssetCount    int32                  `protobuf:"varint,5,opt,name=asset_count,json=assetCount,proto3" json:"asset_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{5}
}

func (x *Wallet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wallet) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Wallet) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *Wallet) GetTotalUsdValue() float64 {
	if x != nil {
		return x.TotalUsdValue
	}
	return 0
}

func (x *Wallet) GetAssetCount() int32 {
	if x != nil {
		return x.AssetCount
	}
	return 0
}

type GetPortfolioSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioSummaryRequest) Reset() {
	*x = GetPortfolioSummaryRequest{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioSummaryRequest) ProtoMessage() {}

func (x *GetPortfolioSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetPortfolioSummaryRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{6}
}

func (x *GetPortfolioSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPortfolioSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallets       []*Wallet              `protobuf:"bytes,1,rep,name=wallets,proto3" json:"wallets,omitempty"`
	TotalNetWorth float64                `protobuf:"fixed64,2,opt,name=total_net_worth,json=totalNetWorth,proto3" json:"total_net_worth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioSummaryResponse) Reset() {
	*x = GetPortfolioSummaryResponse{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioSummaryResponse) ProtoMessage() {}

func (x *GetPortfolioSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetPortfolioSummaryResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{7}
}

func (x *GetPortfolioSummaryResponse) GetWallets() []*Wallet {
	if x != nil {
		return x.Wallets
	}
	return nil
}

func (x *GetPortfolioSummaryResponse) GetTotalNetWorth() float64 {
	if x != nil {
		return x.TotalNetWorth
	}
	return 0
}

type GetWalletDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletDetailsRequest) Reset() {
	*x = GetWalletDetailsRequest{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletDetailsRequest) ProtoMessage() {}

func (x *GetWalletDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetWalletDetailsRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{8}
}

func (x *GetWalletDetailsRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *GetWalletDetailsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetWalletDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Chain         string                 `protobuf:"bytes,3,opt,name=chain,proto3" json:"chain,omitempty"`
	Assets        []*Asset               `protobuf:"bytes,4,rep,name=assets,proto3" json:"assets,omitempty"`
	TotalUsdValue float64                `protobuf:"fixed64,5,opt,name=total_usd_value,json=totalUsdValue,proto3" json:"total_usd_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletDetailsResponse) Reset() {
	*x = GetWalletDetailsResponse{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletDetailsResponse) ProtoMessage() {}

func (x *GetWalletDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetWalletDetailsResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{9}
}

func (x *GetWalletDetailsResponse) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *GetWalletDetailsResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetWalletDetailsResponse) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *GetWalletDetailsResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *GetWalletDetailsResponse) GetTotalUsdValue() float64 {
	if x != nil {
		return x.TotalUsdValue
	}
	return 0
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Symbol        string                 `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TokenAddress  string                 `protobuf:"bytes,6,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type          string                 `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{10}
}

func (x *Transaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Transaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Transaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Transaction) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Transaction) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *Transaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetTransactionHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	FilterByType  string                 `protobuf:"bytes,5,opt,name=filter_by_type,json=filterByType,proto3" json:"filter_by_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryRequest) Reset() {
	*x = GetTransactionHistoryRequest{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryRequest) ProtoMessage() {}

func (x *GetTransactionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{11}
}

func (x *GetTransactionHistoryRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *GetTransactionHistoryRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetTransactionHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTransactionHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTransactionHistoryRequest) GetFilterByType() string {
	if x != nil {
		return x.FilterByType
	}
	return ""
}

type GetTransactionHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryResponse) Reset() {
	*x = GetTransactionHistoryResponse{}
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryResponse) ProtoMessage() {}

func (x *GetTransactionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_v1_portfolio_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_v1_portfolio_proto_rawDescGZIP(), []int{12}
}

func (x *GetTransactionHistoryResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetTransactionHistoryResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTransactionHistoryResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_portfolio_v1_portfolio_proto protoreflect.FileDescriptor

const file_portfolio_v1_portfolio_proto_rawDesc = "" +
	"\n" +
	"\x1cportfolio/v1/portfolio.proto\x12\fportfolio.v1\"2\n" +
	"\x13GetPortfolioRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"\x8d\x01\n" +
	"\x05Asset\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1b\n" +
	"\tusd_value\x18\x05 \x01(\x01R\busdValue\"\x88\x01\n" +
	"\x14GetPortfolioResponse\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12+\n" +
	"\x06assets\x18\x02 \x03(\v2\x13.portfolio.v1.AssetR\x06assets\x12&\n" +
	"\x0ftotal_usd_value\x18\x03 \x01(\x01R\rtotalUsdValue\"`\n" +
	"\rExportRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x122\n" +
	"\x06format\x18\x02 \x01(\x0e2\x1a.portfolio.v1.ExportFormatR\x06format\"$\n" +
	"\x0eExportResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x91\x01\n" +
	"\x06Wallet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05chain\x18\x03 \x01(\tR\x05chain\x12&\n" +
	"\x0ftotal_usd_value\x18\x04 \x01(\x01R\rtotalUsdValue\x12\x1f\n" +
	"\vasset_count\x18\x05 \x01(\x05R\n" +
	"assetCount\"5\n" +
	"\x1aGetPortfolioSummaryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"u\n" +
	"\x1bGetPortfolioSummaryResponse\x12.\n" +
	"\awallets\x18\x01 \x03(\v2\x14.portfolio.v1.WalletR\awallets\x12&\n" +
	"\x0ftotal_net_worth\x18\x02 \x01(\x01R\rtotalNetWorth\"P\n" +
	"\x17GetWalletDetailsRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xbc\x01\n" +
	"\x18GetWalletDetailsResponse\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05chain\x18\x03 \x01(\tR\x05chain\x12+\n" +
	"\x06assets\x18\x04 \x03(\v2\x13.portfolio.v1.AssetR\x06assets\x12&\n" +
	"\x0ftotal_usd_value\x18\x05 \x01(\x01R\rtotalUsdValue\"\xcc\x01\n" +
	"\vTransaction\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x16\n" +
	"\x06symbol\x18\x05 \x01(\tR\x06symbol\x12#\n" +
	"\rtoken_address\x18\x06 \x01(\tR\ftokenAddress\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\"\xa5\x01\n" +
	"\x1cGetTransactionHistoryRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12$\n" +
	"\x0efilter_by_type\x18\x05 \x01(\tR\ffilterByType\"\xa9\x01\n" +
	"\x1dGetTransactionHistoryResponse\x12=\n" +
	"\ftransactions\x18\x01 \x03(\v2\x19.portfolio.v1.TransactionR\ftransactions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit*\\\n" +
	"\fExportFormat\x12\x1d\n" +
	"\x19EXPORT_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EXPORT_FORMAT_CSV\x10\x01\x12\x16\n" +
	"\x12EXPORT_FORMAT_JSON\x10\x022\xef\x03\n" +
	"\x10PortfolioService\x12U\n" +
	"\fGetPortfolio\x12!.portfolio.v1.GetPortfolioRequest\x1a\".portfolio.v1.GetPortfolioResponse\x12j\n" +
	"\x13GetPortfolioSummary\x12(.portfolio.v1.GetPortfolioSummaryRequest\x1a).portfolio.v1.GetPortfolioSummaryResponse\x12a\n" +
	"\x10GetWalletDetails\x12%.portfolio.v1.GetWalletDetailsRequest\x1a&.portfolio.v1.GetWalletDetailsResponse\x12p\n" +
	"\x15GetTransactionHistory\x12*.portfolio.v1.GetTransactionHistoryRequest\x1a+.portfolio.v1.GetTransactionHistoryResponse\x12C\n" +
	"\x06Export\x12\x1b.portfolio.v1.ExportRequest\x1a\x1c.portfolio.v1.ExportResponseB[ZYgithub.com/aezizhu/million-dollar-hunter/services/portfolio-service/proto/portfolio/v1;v1b\x06proto3"

var (
	file_portfolio_v1_portfolio_proto_rawDescOnce sync.Once
	file_portfolio_v1_portfolio_proto_rawDescData []byte
)

func file_portfolio_v1_portfolio_proto_rawDescGZIP() []byte {
	file_portfolio_v1_portfolio_proto_rawDescOnce.Do(func() {
		file_portfolio_v1_portfolio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_portfolio_v1_portfolio_proto_rawDesc), len(file_portfolio_v1_portfolio_proto_rawDesc)))
	})
	return file_portfolio_v1_portfolio_proto_rawDescData
}

var file_portfolio_v1_portfolio_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_portfolio_v1_portfolio_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_portfolio_v1_portfolio_proto_goTypes = []any{
	(ExportFormat)(0),                     // 0: portfolio.v1.ExportFormat
	(*GetPortfolioRequest)(nil),           // 1: portfolio.v1.GetPortfolioRequest
	(*Asset)(nil),                         // 2: portfolio.v1.Asset
	(*GetPortfolioResponse)(nil),          // 3: portfolio.v1.GetPortfolioResponse
	(*ExportRequest)(nil),                 // 4: portfolio.v1.ExportRequest
	(*ExportResponse)(nil),                // 5: portfolio.v1.ExportResponse
	(*Wallet)(nil),                        // 6: portfolio.v1.Wallet
	(*GetPortfolioSummaryRequest)(nil),    // 7: portfolio.v1.GetPortfolioSummaryRequest
	(*GetPortfolioSummaryResponse)(nil),   // 8: portfolio.v1.GetPortfolioSummaryResponse
	(*GetWalletDetailsRequest)(nil),       // 9: portfolio.v1.GetWalletDetailsRequest
	(*GetWalletDetailsResponse)(nil),      // 10: portfolio.v1.GetWalletDetailsResponse
	(*Transaction)(nil),                   // 11: portfolio.v1.Transaction
	(*GetTransactionHistoryRequest)(nil),  // 12: portfolio.v1.GetTransactionHistoryRequest
	(*GetTransactionHistoryResponse)(nil), // 13: portfolio.v1.GetTransactionHistoryResponse
}
var file_portfolio_v1_portfolio_proto_depIdxs = []int32{
	2,  // 0: portfolio.v1.GetPortfolioResponse.assets:type_name -> portfolio.v1.Asset
	0,  // 1: portfolio.v1.ExportRequest.format:type_name -> portfolio.v1.ExportFormat
	6,  // 2: portfolio.v1.GetPortfolioSummaryResponse.wallets:type_name -> portfolio.v1.Wallet
	2,  // 3: portfolio.v1.GetWalletDetailsResponse.assets:type_name -> portfolio.v1.Asset
	11, // 4: portfolio.v1.GetTransactionHistoryResponse.transactions:type_name -> portfolio.v1.Transaction
	1,  // 5: portfolio.v1.PortfolioService.GetPortfolio:input_type -> portfolio.v1.GetPortfolioRequest
	7,  // 6: portfolio.v1.PortfolioService.GetPortfolioSummary:input_type -> portfolio.v1.GetPortfolioSummaryRequest
	9,  // 7: portfolio.v1.PortfolioService.GetWalletDetails:input_type -> portfolio.v1.GetWalletDetailsRequest
	12, // 8: portfolio.v1.PortfolioService.GetTransactionHistory:input_type -> portfolio.v1.GetTransactionHistoryRequest
	4,  // 9: portfolio.v1.PortfolioService.Export:input_type -> portfolio.v1.ExportRequest
	3,  // 10: portfolio.v1.PortfolioService.GetPortfolio:output_type -> portfolio.v1.GetPortfolioResponse
	8,  // 11: portfolio.v1.PortfolioService.GetPortfolioSummary:output_type -> portfolio.v1.GetPortfolioSummaryResponse
	10, // 12: portfolio.v1.PortfolioService.GetWalletDetails:output_type -> portfolio.v1.GetWalletDetailsResponse
	13, // 13: portfolio.v1.PortfolioService.GetTransactionHistory:output_type -> portfolio.v1.GetTransactionHistoryResponse
	5,  // 14: portfolio.v1.PortfolioService.Export:output_type -> portfolio.v1.ExportResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_portfolio_v1_portfolio_proto_init() }
func file_portfolio_v1_portfolio_proto_init() {
	if File_portfolio_v1_portfolio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_portfolio_v1_portfolio_proto_rawDesc), len(file_portfolio_v1_portfolio_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_portfolio_v1_portfolio_proto_goTypes,
		DependencyIndexes: file_portfolio_v1_portfolio_proto_depIdxs,
		EnumInfos:         file_portfolio_v1_portfolio_proto_enumTypes,
		MessageInfos:      file_portfolio_v1_portfolio_proto_msgTypes,
	}.Build()
	File_portfolio_v1_portfolio_proto = out.File
	file_portfolio_v1_portfolio_proto_goTypes = nil
	file_portfolio_v1_portfolio_proto_depIdxs = nil
}
