// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: api/proto/market_data.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTokenPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"` // e.g., "bsc", "solana"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenPriceRequest) Reset() {
	*x = GetTokenPriceRequest{}
	mi := &file_api_proto_market_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenPriceRequest) ProtoMessage() {}

func (x *GetTokenPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_market_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenPriceRequest.ProtoReflect.Descriptor instead.
func (*GetTokenPriceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_market_data_proto_rawDescGZIP(), []int{0}
}

func (x *GetTokenPriceRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *GetTokenPriceRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type GetTokenPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	UsdPrice      float64                `protobuf:"fixed64,3,opt,name=usd_price,json=usdPrice,proto3" json:"usd_price,omitempty"`
	LastUpdated   int64                  `protobuf:"varint,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"` // Unix timestamp
	FromCache     bool                   `protobuf:"varint,5,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenPriceResponse) Reset() {
	*x = GetTokenPriceResponse{}
	mi := &file_api_proto_market_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenPriceResponse) ProtoMessage() {}

func (x *GetTokenPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_market_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenPriceResponse.ProtoReflect.Descriptor instead.
func (*GetTokenPriceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_market_data_proto_rawDescGZIP(), []int{1}
}

func (x *GetTokenPriceResponse) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *GetTokenPriceResponse) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *GetTokenPriceResponse) GetUsdPrice() float64 {
	if x != nil {
		return x.UsdPrice
	}
	return 0
}

func (x *GetTokenPriceResponse) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *GetTokenPriceResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

type GetTokenPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*TokenIdentifier     `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenPricesRequest) Reset() {
	*x = GetTokenPricesRequest{}
	mi := &file_api_proto_market_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenPricesRequest) ProtoMessage() {}

func (x *GetTokenPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_market_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenPricesRequest.ProtoReflect.Descriptor instead.
func (*GetTokenPricesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_market_data_proto_rawDescGZIP(), []int{2}
}

func (x *GetTokenPricesRequest) GetTokens() []*TokenIdentifier {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type TokenIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenIdentifier) Reset() {
	*x = TokenIdentifier{}
	mi := &file_api_proto_market_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenIdentifier) ProtoMessage() {}

func (x *TokenIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_market_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenIdentifier.ProtoReflect.Descriptor instead.
func (*TokenIdentifier) Descriptor() ([]byte, []int) {
	return file_api_proto_market_data_proto_rawDescGZIP(), []int{3}
}

func (x *TokenIdentifier) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *TokenIdentifier) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type GetTokenPricesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prices        []*TokenPrice          `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenPricesResponse) Reset() {
	*x = GetTokenPricesResponse{}
	mi := &file_api_proto_market_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenPricesResponse) ProtoMessage() {}

func (x *GetTokenPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_market_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenPricesResponse.ProtoReflect.Descriptor instead.
func (*GetTokenPricesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_market_data_proto_rawDescGZIP(), []int{4}
}

func (x *GetTokenPricesResponse) GetPrices() []*TokenPrice {
	if x != nil {
		return x.Prices
	}
	return nil
}

type TokenPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	UsdPrice      float64                `protobuf:"fixed64,3,opt,name=usd_price,json=usdPrice,proto3" json:"usd_price,omitempty"`
	LastUpdated   int64                  `protobuf:"varint,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	FromCache     bool                   `protobuf:"varint,5,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPrice) Reset() {
	*x = TokenPrice{}
	mi := &file_api_proto_market_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPrice) ProtoMessage() {}

func (x *TokenPrice) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_market_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPrice.ProtoReflect.Descriptor instead.
func (*TokenPrice) Descriptor() ([]byte, []int) {
	return file_api_proto_market_data_proto_rawDescGZIP(), []int{5}
}

func (x *TokenPrice) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *TokenPrice) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *TokenPrice) GetUsdPrice() float64 {
	if x != nil {
		return x.UsdPrice
	}
	return 0
}

func (x *TokenPrice) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *TokenPrice) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

type GetMarketDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketDataRequest) Reset() {
	*x = GetMarketDataRequest{}
	mi := &file_api_proto_market_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketDataRequest) ProtoMessage() {}

func (x *GetMarketDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_market_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketDataRequest.ProtoReflect.Descriptor instead.
func (*GetMarketDataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_market_data_proto_rawDescGZIP(), []int{6}
}

func (x *GetMarketDataRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *GetMarketDataRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type GetMarketDataResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress    string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Chain           string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	UsdPrice        float64                `protobuf:"fixed64,3,opt,name=usd_price,json=usdPrice,proto3" json:"usd_price,omitempty"`
	MarketCap       float64                `protobuf:"fixed64,4,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	Volume_24H      float64                `protobuf:"fixed64,5,opt,name=volume_24h,json=volume24h,proto3" json:"volume_24h,omitempty"`
	PriceChange_24H float64                `protobuf:"fixed64,6,opt,name=price_change_24h,json=priceChange24h,proto3" json:"price_change_24h,omitempty"`
	LastUpdated     int64                  `protobuf:"varint,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	FromCache       bool                   `protobuf:"varint,8,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMarketDataResponse) Reset() {
	*x = GetMarketDataResponse{}
	mi := &file_api_proto_market_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketDataResponse) ProtoMessage() {}

func (x *GetMarketDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_market_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketDataResponse.ProtoReflect.Descriptor instead.
func (*GetMarketDataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_market_data_proto_rawDescGZIP(), []int{7}
}

func (x *GetMarketDataResponse) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *GetMarketDataResponse) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *GetMarketDataResponse) GetUsdPrice() float64 {
	if x != nil {
		return x.UsdPrice
	}
	return 0
}

func (x *GetMarketDataResponse) GetMarketCap() float64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

func (x *GetMarketDataResponse) GetVolume_24H() float64 {
	if x != nil {
		return x.Volume_24H
	}
	return 0
}

func (x *GetMarketDataResponse) GetPriceChange_24H() float64 {
	if x != nil {
		return x.PriceChange_24H
	}
	return 0
}

func (x *GetMarketDataResponse) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *GetMarketDataResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

type RefreshTokenPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenPriceRequest) Reset() {
	*x = RefreshTokenPriceRequest{}
	mi := &file_api_proto_market_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenPriceRequest) ProtoMessage() {}

func (x *RefreshTokenPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_market_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenPriceRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenPriceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_market_data_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshTokenPriceRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *RefreshTokenPriceRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type RefreshTokenPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UsdPrice      float64                `protobuf:"fixed64,3,opt,name=usd_price,json=usdPrice,proto3" json:"usd_price,omitempty"`
	LastUpdated   int64                  `protobuf:"varint,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenPriceResponse) Reset() {
	*x = RefreshTokenPriceResponse{}
	mi := &file_api_proto_market_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenPriceResponse) ProtoMessage() {}

func (x *RefreshTokenPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_market_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenPriceResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenPriceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_market_data_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshTokenPriceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshTokenPriceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RefreshTokenPriceResponse) GetUsdPrice() float64 {
	if x != nil {
		return x.UsdPrice
	}
	return 0
}

func (x *RefreshTokenPriceResponse) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

var File_api_proto_market_data_proto protoreflect.FileDescriptor

const file_api_proto_market_data_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/market_data.proto\x12\n" +
	"marketdata\"Q\n" +
	"\x14GetTokenPriceRequest\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\"\xb1\x01\n" +
	"\x15GetTokenPriceResponse\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x1b\n" +
	"\tusd_price\x18\x03 \x01(\x01R\busdPrice\x12!\n" +
	"\flast_updated\x18\x04 \x01(\x03R\vlastUpdated\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x05 \x01(\bR\tfromCache\"L\n" +
	"\x15GetTokenPricesRequest\x123\n" +
	"\x06tokens\x18\x01 \x03(\v2\x1b.marketdata.TokenIdentifierR\x06tokens\"L\n" +
	"\x0fTokenIdentifier\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\"H\n" +
	"\x16GetTokenPricesResponse\x12.\n" +
	"\x06prices\x18\x01 \x03(\v2\x16.marketdata.TokenPriceR\x06prices\"\xa6\x01\n" +
	"\n" +
	"TokenPrice\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x1b\n" +
	"\tusd_price\x18\x03 \x01(\x01R\busdPrice\x12!\n" +
	"\flast_updated\x18\x04 \x01(\x03R\vlastUpdated\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x05 \x01(\bR\tfromCache\"Q\n" +
	"\x14GetMarketDataRequest\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\"\x99\x02\n" +
	"\x15GetMarketDataResponse\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x1b\n" +
	"\tusd_price\x18\x03 \x01(\x01R\busdPrice\x12\x1d\n" +
	"\n" +
	"market_cap\x18\x04 \x01(\x01R\tmarketCap\x12\x1d\n" +
	"\n" +
	"volume_24h\x18\x05 \x01(\x01R\tvolume24h\x12(\n" +
	"\x10price_change_24h\x18\x06 \x01(\x01R\x0epriceChange24h\x12!\n" +
	"\flast_updated\x18\a \x01(\x03R\vlastUpdated\x12\x1d\n" +
	"\n" +
	"from_cache\x18\b \x01(\bR\tfromCache\"U\n" +
	"\x18RefreshTokenPriceRequest\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\"\x8f\x01\n" +
	"\x19RefreshTokenPriceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tusd_price\x18\x03 \x01(\x01R\busdPrice\x12!\n" +
	"\flast_updated\x18\x04 \x01(\x03R\vlastUpdated2\xfa\x02\n" +
	"\x11MarketDataService\x12T\n" +
	"\rGetTokenPrice\x12 .marketdata.GetTokenPriceRequest\x1a!.marketdata.GetTokenPriceResponse\x12W\n" +
	"\x0eGetTokenPrices\x12!.marketdata.GetTokenPricesRequest\x1a\".marketdata.GetTokenPricesResponse\x12T\n" +
	"\rGetMarketData\x12 .marketdata.GetMarketDataRequest\x1a!.marketdata.GetMarketDataResponse\x12`\n" +
	"\x11RefreshTokenPrice\x12$.marketdata.RefreshTokenPriceRequest\x1a%.marketdata.RefreshTokenPriceResponseBNZLgithub.com/aezizhu/million-dollar-hunter/services/market-data-service/pkg/pbb\x06proto3"

var (
	file_api_proto_market_data_proto_rawDescOnce sync.Once
	file_api_proto_market_data_proto_rawDescData []byte
)

func file_api_proto_market_data_proto_rawDescGZIP() []byte {
	file_api_proto_market_data_proto_rawDescOnce.Do(func() {
		file_api_proto_market_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_market_data_proto_rawDesc), len(file_api_proto_market_data_proto_rawDesc)))
	})
	return file_api_proto_market_data_proto_rawDescData
}

var file_api_proto_market_data_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_market_data_proto_goTypes = []any{
	(*GetTokenPriceRequest)(nil),      // 0: marketdata.GetTokenPriceRequest
	(*GetTokenPriceResponse)(nil),     // 1: marketdata.GetTokenPriceResponse
	(*GetTokenPricesRequest)(nil),     // 2: marketdata.GetTokenPricesRequest
	(*TokenIdentifier)(nil),           // 3: marketdata.TokenIdentifier
	(*GetTokenPricesResponse)(nil),    // 4: marketdata.GetTokenPricesResponse
	(*TokenPrice)(nil),                // 5: marketdata.TokenPrice
	(*GetMarketDataRequest)(nil),      // 6: marketdata.GetMarketDataRequest
	(*GetMarketDataResponse)(nil),     // 7: marketdata.GetMarketDataResponse
	(*RefreshTokenPriceRequest)(nil),  // 8: marketdata.RefreshTokenPriceRequest
	(*RefreshTokenPriceResponse)(nil), // 9: marketdata.RefreshTokenPriceResponse
}
var file_api_proto_market_data_proto_depIdxs = []int32{
	3, // 0: marketdata.GetTokenPricesRequest.tokens:type_name -> marketdata.TokenIdentifier
	5, // 1: marketdata.GetTokenPricesResponse.prices:type_name -> marketdata.TokenPrice
	0, // 2: marketdata.MarketDataService.GetTokenPrice:input_type -> marketdata.GetTokenPriceRequest
	2, // 3: marketdata.MarketDataService.GetTokenPrices:input_type -> marketdata.GetTokenPricesRequest
	6, // 4: marketdata.MarketDataService.GetMarketData:input_type -> marketdata.GetMarketDataRequest
	8, // 5: marketdata.MarketDataService.RefreshTokenPrice:input_type -> marketdata.RefreshTokenPriceRequest
	1, // 6: marketdata.MarketDataService.GetTokenPrice:output_type -> marketdata.GetTokenPriceResponse
	4, // 7: marketdata.MarketDataService.GetTokenPrices:output_type -> marketdata.GetTokenPricesResponse
	7, // 8: marketdata.MarketDataService.GetMarketData:output_type -> marketdata.GetMarketDataResponse
	9, // 9: marketdata.MarketDataService.RefreshTokenPrice:output_type -> marketdata.RefreshTokenPriceResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_market_data_proto_init() }
func file_api_proto_market_data_proto_init() {
	if File_api_proto_market_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_market_data_proto_rawDesc), len(file_api_proto_market_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_market_data_proto_goTypes,
		DependencyIndexes: file_api_proto_market_data_proto_depIdxs,
		MessageInfos:      file_api_proto_market_data_proto_msgTypes,
	}.Build()
	File_api_proto_market_data_proto = out.File
	file_api_proto_market_data_proto_goTypes = nil
	file_api_proto_market_data_proto_depIdxs = nil
}
