// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: api/proto/market_data.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketDataService_GetTokenPrice_FullMethodName     = "/marketdata.MarketDataService/GetTokenPrice"
	MarketDataService_GetTokenPrices_FullMethodName    = "/marketdata.MarketDataService/GetTokenPrices"
	MarketDataService_GetMarketData_FullMethodName     = "/marketdata.MarketDataService/GetMarketData"
	MarketDataService_RefreshTokenPrice_FullMethodName = "/marketdata.MarketDataService/RefreshTokenPrice"
)

// MarketDataServiceClient is the client API for MarketDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MarketDataService provides real-time and cached cryptocurrency market data
type MarketDataServiceClient interface {
	// GetTokenPrice retrieves the current USD price for a specific token
	GetTokenPrice(ctx context.Context, in *GetTokenPriceRequest, opts ...grpc.CallOption) (*GetTokenPriceResponse, error)
	// GetTokenPrices retrieves prices for multiple tokens in a single request
	GetTokenPrices(ctx context.Context, in *GetTokenPricesRequest, opts ...grpc.CallOption) (*GetTokenPricesResponse, error)
	// GetMarketData retrieves comprehensive market data for a token
	GetMarketData(ctx context.Context, in *GetMarketDataRequest, opts ...grpc.CallOption) (*GetMarketDataResponse, error)
	// RefreshTokenPrice forces a refresh of a token's price from CoinGecko
	RefreshTokenPrice(ctx context.Context, in *RefreshTokenPriceRequest, opts ...grpc.CallOption) (*RefreshTokenPriceResponse, error)
}

type marketDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketDataServiceClient(cc grpc.ClientConnInterface) MarketDataServiceClient {
	return &marketDataServiceClient{cc}
}

func (c *marketDataServiceClient) GetTokenPrice(ctx context.Context, in *GetTokenPriceRequest, opts ...grpc.CallOption) (*GetTokenPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenPriceResponse)
	err := c.cc.Invoke(ctx, MarketDataService_GetTokenPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) GetTokenPrices(ctx context.Context, in *GetTokenPricesRequest, opts ...grpc.CallOption) (*GetTokenPricesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenPricesResponse)
	err := c.cc.Invoke(ctx, MarketDataService_GetTokenPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) GetMarketData(ctx context.Context, in *GetMarketDataRequest, opts ...grpc.CallOption) (*GetMarketDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketDataResponse)
	err := c.cc.Invoke(ctx, MarketDataService_GetMarketData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) RefreshTokenPrice(ctx context.Context, in *RefreshTokenPriceRequest, opts ...grpc.CallOption) (*RefreshTokenPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenPriceResponse)
	err := c.cc.Invoke(ctx, MarketDataService_RefreshTokenPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketDataServiceServer is the server API for MarketDataService service.
// All implementations must embed UnimplementedMarketDataServiceServer
// for forward compatibility.
//
// MarketDataService provides real-time and cached cryptocurrency market data
type MarketDataServiceServer interface {
	// GetTokenPrice retrieves the current USD price for a specific token
	GetTokenPrice(context.Context, *GetTokenPriceRequest) (*GetTokenPriceResponse, error)
	// GetTokenPrices retrieves prices for multiple tokens in a single request
	GetTokenPrices(context.Context, *GetTokenPricesRequest) (*GetTokenPricesResponse, error)
	// GetMarketData retrieves comprehensive market data for a token
	GetMarketData(context.Context, *GetMarketDataRequest) (*GetMarketDataResponse, error)
	// RefreshTokenPrice forces a refresh of a token's price from CoinGecko
	RefreshTokenPrice(context.Context, *RefreshTokenPriceRequest) (*RefreshTokenPriceResponse, error)
	mustEmbedUnimplementedMarketDataServiceServer()
}

// UnimplementedMarketDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketDataServiceServer struct{}

func (UnimplementedMarketDataServiceServer) GetTokenPrice(context.Context, *GetTokenPriceRequest) (*GetTokenPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenPrice not implemented")
}
func (UnimplementedMarketDataServiceServer) GetTokenPrices(context.Context, *GetTokenPricesRequest) (*GetTokenPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenPrices not implemented")
}
func (UnimplementedMarketDataServiceServer) GetMarketData(context.Context, *GetMarketDataRequest) (*GetMarketDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketData not implemented")
}
func (UnimplementedMarketDataServiceServer) RefreshTokenPrice(context.Context, *RefreshTokenPriceRequest) (*RefreshTokenPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshTokenPrice not implemented")
}
func (UnimplementedMarketDataServiceServer) mustEmbedUnimplementedMarketDataServiceServer() {}
func (UnimplementedMarketDataServiceServer) testEmbeddedByValue()                           {}

// UnsafeMarketDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketDataServiceServer will
// result in compilation errors.
type UnsafeMarketDataServiceServer interface {
	mustEmbedUnimplementedMarketDataServiceServer()
}

func RegisterMarketDataServiceServer(s grpc.ServiceRegistrar, srv MarketDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedMarketDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketDataService_ServiceDesc, srv)
}

func _MarketDataService_GetTokenPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetTokenPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetTokenPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetTokenPrice(ctx, req.(*GetTokenPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_GetTokenPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetTokenPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetTokenPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetTokenPrices(ctx, req.(*GetTokenPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_GetMarketData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetMarketData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetMarketData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetMarketData(ctx, req.(*GetMarketDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_RefreshTokenPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).RefreshTokenPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_RefreshTokenPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).RefreshTokenPrice(ctx, req.(*RefreshTokenPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketDataService_ServiceDesc is the grpc.ServiceDesc for MarketDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marketdata.MarketDataService",
	HandlerType: (*MarketDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTokenPrice",
			Handler:    _MarketDataService_GetTokenPrice_Handler,
		},
		{
			MethodName: "GetTokenPrices",
			Handler:    _MarketDataService_GetTokenPrices_Handler,
		},
		{
			MethodName: "GetMarketData",
			Handler:    _MarketDataService_GetMarketData_Handler,
		},
		{
			MethodName: "RefreshTokenPrice",
			Handler:    _MarketDataService_RefreshTokenPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/market_data.proto",
}
